
import fs from 'fs';
import os from 'os';
import path from 'path';

// ------------------------------------------------------------------
// AUTO-DETECT ANDROID SDK PATH
// ------------------------------------------------------------------

const platform = os.platform();
const homeDir = os.homedir();

let sdkPath = '';

console.log(`🖥️  OS Detected: ${platform}`);
console.log(`🏠 Home Directory: ${homeDir}`);

if (platform === 'win32') {
  // Windows Default: C:\Users\<User>\AppData\Local\Android\Sdk
  // We use forward slashes '/' because Gradle prefers them even on Windows
  sdkPath = path.join(homeDir, 'AppData', 'Local', 'Android', 'Sdk').replace(/\\/g, '/');
} else if (platform === 'darwin') {
  // macOS Default: /Users/<User>/Library/Android/sdk
  sdkPath = path.join(homeDir, 'Library', 'Android', 'sdk');
} else {
  // Linux Default: /home/<User>/Android/Sdk
  sdkPath = path.join(homeDir, 'Android', 'Sdk');
}

const androidDir = path.join(process.cwd(), 'android');
const localPropertiesPath = path.join(androidDir, 'local.properties');

// Check if android folder exists
if (!fs.existsSync(androidDir)) {
  console.error('❌ Error: "android" directory not found.');
  console.error('   Please run "npx cap add android" before running this script.');
  process.exit(1);
}

// Create the file content
const content = `## This file is automatically generated by fix-android.js
sdk.dir=${sdkPath}
`;

try {
  fs.writeFileSync(localPropertiesPath, content);
  console.log('--------------------------------------------------');
  console.log(`✅ SUCCESS: Created local.properties`);
  console.log(`📂 SDK Path set to: ${sdkPath}`);
  console.log('--------------------------------------------------');
  console.log('🚀 You can now run "npx cap open android" and build the app!');
} catch (err) {
  console.error('❌ Failed to write local.properties:', err);
}
